// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/common/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardContainer: typeof import('./src/components/Pay/CardContainer.vue')['default']
    CardElement: typeof import('./src/components/CardElement.vue')['default']
    FacebookLogin: typeof import('./src/components/SocialLogin/FacebookLogin.vue')['default']
    GithubLogin: typeof import('./src/components/SocialLogin/GithubLogin.vue')['default']
    GoogleLogin: typeof import('./src/components/SocialLogin/GoogleLogin.vue')['default']
    HomeLayout: typeof import('./src/views/layouts/HomeLayout.vue')['default']
    Input: typeof import('./src/components/common/Input.vue')['default']
    LoginPage: typeof import('./src/views/auth/LoginPage.vue')['default']
    Logo: typeof import('./src/components/common/Logo.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PayButtonPage: typeof import('./src/views/pay/PayButtonPage.vue')['default']
    RegisterPage: typeof import('./src/views/auth/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCardPage: typeof import('./src/views/pay/SelectCardPage.vue')['default']
    SelectCarPage: typeof import('./src/views/pay/SelectCarPage.vue')['default']
  }
}
