// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/common/Button.vue')['default']
    Card: typeof import('./src/components/common/card/Card.vue')['default']
    CardContainer: typeof import('./src/components/Pay/CardContainer.vue')['default']
    CardElement: typeof import('./src/components/common/card/CardElement.vue')['default']
    ChoosePlanPage: typeof import('./src/views/auth/ChoosePlanPage.vue')['default']
    CreateCardElement: typeof import('./src/components/common/card/CreateCardElement.vue')['default']
    CreateCarPage: typeof import('./src/views/pay/CreateCarPage.vue')['default']
    CreditCardCard: typeof import('./src/components/Plan/CreditCardCard.vue')['default']
    FacebookLogin: typeof import('./src/components/SocialLogin/FacebookLogin.vue')['default']
    GithubLogin: typeof import('./src/components/SocialLogin/GithubLogin.vue')['default']
    GoogleLogin: typeof import('./src/components/SocialLogin/GoogleLogin.vue')['default']
    HomeLayout: typeof import('./src/views/layouts/HomeLayout.vue')['default']
    Input: typeof import('./src/components/common/Input.vue')['default']
    LoginPage: typeof import('./src/views/auth/LoginPage.vue')['default']
    Logo: typeof import('./src/components/common/Logo.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    MapLayout: typeof import('./src/views/layouts/MapLayout.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NotFoundPage: typeof import('./src/views/NotFoundPage.vue')['default']
    OtherLayout: typeof import('./src/views/layouts/OtherLayout.vue')['default']
    PayButtonPage: typeof import('./src/views/pay/PayButtonPage.vue')['default']
    PlanCard: typeof import('./src/components/Plan/PlanCard.vue')['default']
    ProfilePage: typeof import('./src/views/profile/ProfilePage.vue')['default']
    RegisterPage: typeof import('./src/views/auth/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCarPage: typeof import('./src/views/pay/SelectCarPage.vue')['default']
    SelectHourPage: typeof import('./src/views/pay/SelectHourPage.vue')['default']
    SelectPage: typeof import('./src/views/pay/SelectPage.vue')['default']
    SwipeableCardElement: typeof import('./src/components/common/card/SwipeableCardElement.vue')['default']
    Toasts: typeof import('./src/components/common/Toasts.vue')['default']
  }
}
