// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GithubLogin: typeof import('./src/components/SocialLogin/GithubLogin.vue')['default']
    GoogleLogin: typeof import('./src/components/SocialLogin/GoogleLogin.vue')['default']
    HomePage: typeof import('./src/views/HomePage.vue')['default']
    LoginPage: typeof import('./src/views/LoginPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
